#!/usr/bin/env python2.6

import commands

rester_path = None
for entry in commands.getoutput("echo ${PATH}").split(':'):
	if entry.count('/rester/') > 0:
		rester_path = entry

if not rester_path:
	print "Please add rester to your path. See the README for details."
	exit()

print commands.getoutput(rester_path + "/rester_build `pwd`")

