#!/usr/bin/env bash


# ignore all warnings
SCRIPT_PATH=/usr/bin/rootintootin_run
python2.6 -W ignore::DeprecationWarning $SCRIPT_PATH `pwd` $@ 'server'

# full python 3.0 warning mode
#python2.6 -3 $SCRIPT_PATH `pwd` $@
