#!/usr/bin/env python2.6

import commands

rootintootin_path = None
for entry in commands.getoutput("echo ${PATH}").split(':'):
	if entry.count('/rootintootin/') > 0:
		rootintootin_path = entry

if not rootintootin_path:
	print "Please add rootintootin to your path. See the README for details."
	exit()

print commands.getoutput(rootintootin_path + "/rootintootin_build `pwd`")

